<input type="hidden" class="base_url" value="<?= getenv('APP_URL') ?>">
<input type="hidden" class="rest_url" value="<?= getenv('APP_REST_URL') ?>">
<input type="hidden" class="assets_url" value="<?= getenv('APP_ASSETS') ?>">
<input type="hidden" class="id_user" value="<?= $this->session->id_user ?>">
<input type="hidden" class="branch_id" value="<?= $this->session->branch_id_user ?>">
<input type="hidden" class="lat_user" value="<?= $this->session->lat_user ?>">
<input type="hidden" class="long_user" value="<?= $this->session->long_user ?>">
<input type="hidden" class="lat_branch" value="<?= $this->session->branch_latitude_user ?>">
<input type="hidden" class="long_branch" value="<?= $this->session->branch_longitude_user ?>">
<input type="hidden" class="time_now" value="<?= date('H:i') ?>">